#
# bSetCargo versão 1.2
# Criador: iBoosterr_
#
## placeholders
# %player% : jogador que vai receber o cargo // setcargo, Lore, Command
# %p-prefix% : prefixo do jogador que vai receber o cargo (necessita de vault) // setcargo, Lore
##

settings:
  starter: "&e■ "

messages:
  noArgs: "&cUtilize /setcargo <usuario>"
  noPermission: "&fComando desconhecido."
  reload: "&aO plugin foi recarregado com sucesso."
  needOnline: "&cO jogador precisa estar online."
  setRole: "&eSetando cargo para %p-prefix%&f%player%&e, listando cargos..."
  bsc:
    - ""
    - "&6&lBSETCARGO &8&l➟&e Ajuda"
    - "&e/setcargo&8&l ➟ &7Setar um cargo."
    - "&e/bsc reload&8&l ➟&7 Recarregar o plugin."
    - ""

roles:
  1:
    name: "&6Master"
    permission: "role.master"
    lore:
      - "          &6&lBSETCARGO\n"
      - "&eSetando cargo &l➟ &6Master\n"
      - "&eJogador &l➟ %p-prefix%&f%player%\n"
      - "\n"
      - "&aClique aqui para setar o cargo."
    command: "/lp user %player% parent add master"
  2:
    name: "&4Gerente"
    permission: "role.gerente"
    lore:
      - "          &6&lBSETCARGO\n"
      - "&eSetando cargo &l➟ &4Gerente\n"
      - "&eJogador &l➟ %p-prefix%&f%player%\n"
      - "\n"
      - "&aClique aqui para setar o cargo."
    command: "/lp user %player% parent add master"
  3:
    name: "&cAdmin"
    permission: "role.admin"
    lore:
      - "          &6&lBSETCARGO\n"
      - "&eSetando cargo &l➟ &cAdmin\n"
      - "&eJogador &l➟ %p-prefix%&f%player%\n"
      - "\n"
      - "&aClique aqui para setar o cargo."
    command: "/lp user %player% parent add master"
