name: bSetCargo
version: 1.0-SNAPSHOT
author: iBoosterr_

main: me.booster.bsetcargo.Main
commands:
  setcargo:
    aliases: [setrole, setarrole, setarcargo, setartag, settag]
    description: "Setar um cargo."
  bsc:
    aliases: [bsetcargo]
    description: "Comando de ajuda do bSetCargo."